// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: './src/infrastructure/projection-store/prisma/schema.prisma',
  migrations: {
    path: './src/infrastructure/projection-store/prisma/migrations',
  },
  datasource: { url: process.env.DATABASE_PROJECTION_STORE_URL! },
});
