#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
  echo "----------------------------------------------------"
  echo "❌ ERROR: Direct commits to the $branch branch are not allowed."
  echo "Please create a new feature branch and use a pull request for changes."
  echo "----------------------------------------------------"
  exit 1
fi

npx lint-staged
